spring:
    data:
        mongodb:
          authentication-database: admin
          username: admin
          password: root
          database: iot_msg
          port: 27017
          host: localhost
